### ISSUE TITLE
Incorrect thermistor constants

### ISSUE THREAD

**Issue by nwf** [adafruit/Adafruit_CCS811#10]
https://github.com/adafruit/Adafruit_CCS811/blob/7ff447cb883b9dc9380edbe00655635be45ba5ed/Adafruit_CCS811.cpp#L164 uses `CCS811_REF_RESISTOR` for the thermistor's resistance at 25C, but the schematic at https://learn.adafruit.com/assets/44639 indicates that this should be 10K, not 100K.

**Comment by ladyada** [comment]
thermistor support was dropped from the firmware anyways :/

**Comment by nwf** [comment]
Well that's unfortunate.  Did they give a rationale?

**Comment by ladyada** [comment]
nope. but its definitely gone

**Comment by caternuson** [comment]
@nwf 100k looks correct?
![ref_res](https://user-images.githubusercontent.com/8755041/60606639-926c9b80-9d70-11e9-9169-e42804876efc.jpg)

@ladyada how does "dropped from firmware" affect `calculateTemperature()`?
https://github.com/adafruit/Adafruit_CCS811/blob/master/Adafruit_CCS811.cpp#L152

**Comment by nwf** [comment]
@caternuson The 100K you so kindly circled corresponds to the use of `CCS811_REF_RESISTOR` on line **161**, which is correct.  I was referring to the use of it on line **164**, which is incorrect, as that should correspond to the resistance of the NTC device just to the right of the circled resistor, which, as you'll see in the schematic, is labeled as 10K, not 100K.
