### ISSUE TITLE
Wrong units in examples (ppm for TVOC)

### ISSUE THREAD

**Issue by mereshow** [adafruit/Adafruit_CCS811#12]
Hi!

In [your web](https://learn.adafruit.com/adafruit-ccs811-air-quality-sensor/overview) you indicate that TVOC is meassured in parts per billion (ppb) but in the examples you use parts per million (ppm). The [CCS811 sensor datasheet, page 9](https://cdn-learn.adafruit.com/assets/assets/000/044/636/original/CCS811_DS000459_2-00-1098798.pdf?1501602769) also indicates that the sensor meassures TVOC in ppb. 
I don't see any TVOC conversion (ppb --> ppm) in your library, so I suppose that the examples display the incorrect units.

Thanks a lot for your work :-)

**Comment by ladyada** [comment]
yep TVOC is in ppb and eCO2 is in ppm

![image](https://user-images.githubusercontent.com/1214161/61654637-db868000-ac8a-11e9-9945-df3b68aa8bbe.png)

**Comment by ladyada** [comment]
where do you see TVOC mentioned in ppm, exactly?

**Comment by mereshow** [comment]
Sorry! I didn't see the comma (that belongs to eCO2), the examples are correct! The TVOC units are not specified:

`Serial.print("ppm, TVOC: ");`

Sorry for wasting your time :-/
