### ISSUE TITLE
Question setTempOffset()

### ISSUE THREAD

**Issue by esp13** [adafruit/Adafruit_CCS811#13]
Hi,

In the example the temperature offset is set by comparing to 25.0

(1)- Why 25.0? Is it supposed to be the average room temperature, so instead of having the real temperature, it takes the 25.0 as average?

(2)- If yes, I could use my BME280 sensor to set the real offset? like this: `ccs.setTempOffset(temp - bme.readTemperature());`?

(3)- I don't really understand this temperature part. The CCS811 chip doesn't have any temperature sensor inside right? On my CCS811 breadboard I don't have any NTC temperature sensor neither I think (didn't see it). So how is this temperature moving?

(4)- When you use setEnvironmentalData() with datas from a BME280, Is the temperature offset still in use? If yes do we need to periodically update the offset `ccs.setTempOffset(temp - bme.readTemperature());`?

Thank for reading and sorry for my poor english level.

**Comment by ladyada** [comment]
it does not anymore - the old chips *used* to have temperature sensor support. it does not anymore, so this is sorta moot. :)

**Comment by esp13** [comment]
Thank you for your fast answer!

(5)- So we can remove all setTempOffset() and calculateTemperature() call inside program?

(6)- What is now returning calculateTemperature()? Cause the returned data is moving.

**Comment by ladyada** [comment]
yes dont use any of thsoe, they do not work with newer chips

**Comment by bernardoafonseca** [comment]
Hi esp13,
did you understand the answer given by ladyada ?
