### ISSUE TITLE
CCS811 performs a crash reset in a few seconds

### ISSUE THREAD

**Issue by wangmings** [adafruit/Adafruit_CCS811#18]
#CCS811 performs a crash reset in a few seconds

CO2: 405ppm, TVOC: 0
CO2: 400ppm, TVOC: 0
CO2: 400ppm, TVOC: 0
CO2: 401ppm, TVOC: 0
ERROR!

Soft WDT reset

>>>stack>>>

ctx: cont
sp: 3ffffdf0 end: 3fffffc0 offset: 01a0
3fffff90:  3fffdad0 3ffee338 3ffee47c 40201435  
3fffffa0:  feefeffe 00000000 3ffee4a4 40202118  
3fffffb0:  feefeffe feefeffe 3ffe84e8 40100e6d  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,1)

load 0x4010f000, len 3456, room 16 
tail 0
chksum 0x84
csum 0x84
va5432625
~ld
CCS811 test
CO2: 0ppm, TVOC: 0
CO2: 0ppm, TVOC: 0
ERROR!

Soft WDT reset

**Comment by ladyada** [comment]
you need to add some delays - visit esp support for help
