### ISSUE TITLE
Why is setDriveMode hardcoded on begin? 

### ISSUE THREAD

**Issue by otmezger** [adafruit/Adafruit_CCS811#28]
Hi, 

is there a reason why `setDriveMode` is hardcoded to 1 sec on `begin`? 
https://github.com/adafruit/Adafruit_CCS811/blob/master/Adafruit_CCS811.cpp#L36

if this is important during begin, is it safe to call `css.setDriveMode()` in `setup()` immediately after 

```
// Wait for the sensor to be ready
  while(!ccs.available());
```
See: https://github.com/adafruit/Adafruit_CCS811/blob/master/examples/CCS811_test/CCS811_test.ino#L34

If this is possible, I would love to modify the example and send a MR to this repository, would you check and merge?

**Comment by ladyada** [comment]
we just want to have *something* on start. you can setDriveMode whenever you like. if you want to send a PR, but if its just for your project, do it for your project.
