### ISSUE TITLE
Adafruit CCS811

### ISSUE THREAD

**Issue by rpiekutowski** [adafruit/Adafruit_CCS811#3]
I am having trouble getting accurate readings with the CCS811, I have already let it burn for 48 hours. I am getting negative results for eCO2 and tVOC, and there is no change once i run the program. Here is my code:

#include <CCS811.h>

#define ADDR      0x5A
#define WAKE_PIN  2

CCS811 sensor;

void setup()
{
  Serial.begin(9600);
}

void loop()
{ 
  //sensor.compensate(22.56, 30.73);  // replace with t and rh values from sensor
  sensor.getData();
  Serial.print("CO2 concentration : "); Serial.print(sensor.readCO2()); Serial.println(" ppm");
  Serial.print("TVOC concentration : "); Serial.print(sensor.readTVOC()); Serial.println(" ppb");
  Serial.println();
  delay(2500);
}

**Comment by ladyada** [comment]
Hiya you are not using our library if that's your code! Please try our library, if you still have issues and you purchased it from adafruit, please post in the forums :)
